# Generated by Django 5.0.7 on 2024-07-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='phone_number',
            field=models.CharField(default=79125921442, max_length=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
